### ISSUE TITLE
Help!!!

### ISSUE THREAD

**Issue by JiweiMaster** [kimmyeongjune/Aicity2024_track5#1]
The organizing committee has not replied to my email. Do you have the data download link for the aicity 2024 track5 track? Thank you

**Comment by kimmyeongjune** [comment]
Hi!
Maybe I have data on my computer, but I can't use my computer right now, so is it okay if I contact you again as soon as it's confirmed?

**Comment by JiweiMaster** [comment]
Thank you very much for your help. If you could send me the dataset today or tomorrow, I would greatly appreciate it. Here is my email address : 20210240276@fudan.edu.cn , thanks again! @kimmyeongjune

**Comment by kimmyeongjune** [comment]
Hi, Jiwei Master
I recently changed my computer and didn't bring data from my old computer, so I can't find it on my computer now. I checked my old computer, but the new user deleted it. I'm sorry I couldn't help you.
